### PR TITLE
support Asia characters & wrap word with hard mode

### PR DESCRIPTION
**Pull request by magicismight**
support Asia characters & wrap word with hard mode

### CODE REVIEW

**Comment by magicismight** [comment]
fix issue #2 
And use hard mode to wrap word, in case the long word break the table

**Comment by tecfu** [comment]
I'd like to acknowledge your contribution and than you for your pull request. Thank you.
However, the changes fail to wrap east asian characters properly given the test below.

```
var Table = require('../');

var header = [
	{
		value : "项目",
	},
	{
		value : "价格",
	},
	{
		value : "有机",
	}
];

//Example with arrays as rows 
var rows = [
	["汉堡包",2.50,null],
	["特制的酱汁",0.10],
	["2玉米饼，大米和豆类，奶酪",9.80,""],
	["苹果片",1.00,"yes"],
	[null,1.50,"no"],
	["意大利粉, 火腿, 意大利干酪",3.75,"no"]
];

var t1 = Table(header,rows,{
	borderStyle : 1,
	paddingBottom : 0,
	headerAlign : "center",
	align : "center",
	color : "white"
});

str1 = t1.render();
console.log(str1);
```

Using bash in Ubuntu 14.04, the result is something like:

output

That's because you're changes don't actually alter where the string is wrapped, which is actually inside the <b>wordwrap</b> module, which is called on lines 204-205:

```
var wrap = wordwrap.hard(innerWidth);
		string = wrap(string); 
```

By the time your change on line 232 is called, the string has already been wrapped at 205. As the code sits now, the way to really address this problem is to add east asian character support to the <b>wordwrap</b> module - or find a replacement wrapping method that addresses this issue already.

**Comment by magicismight** [comment]
fixed Asian characters wrap issue.
works


Works for me on Centos 6.6.

btw:
I used wordwrap.hard to wrap somthing like a url or a token key which is too long.
Not for Asian characters.
just like last line in the first img.
otherwise it will break table like this.
wrap

And.
There is another issue on Centos.
```
{borderStyle: 1}
```
border style 1 works funny on centos for the characters like: ┌ presents 2 characters width on centos.
borderstyle

**Comment by tecfu** [comment]
Thanks for your contribution!

**Comment by tecfu** [comment]
Unfortunately, your contribution wasn't recorded under the contributors for the project - which is something I would have liked. 

This may have to do with issues surrounding your conflicts in your github account's email address, or possibly have to do with the fact that you didn't star this project:

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by magicismight** [comment]
That`s alright.
Just stared.

**Comment by tecfu** [comment]
That was a clever workaround, thanks again. If you are interested in being a collaborator let me know and I'll give you push privileges.

**Comment by magicismight** [comment]
thx!
I'd love to.

**Comment by tecfu** [comment]
Ok, done. Welcome aboard.

**Pull request merged**
